### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by revodavid** [wcornwell/earthtones#5]
I had to install several packages before I could get `get_earthtones` to run. Here's the script I used

``` r
if (!require(devtools))
    install.packages("devtools")
devtools::install_github("wcornwell/earthtones")
install.packages("RgoogleMaps")
install.packages("geosphere")
install.packages("jpeg")
install.packages("mapproj")
install.packages("proto")
install.packages("rjson")
library("earthtones")

#chicago 41.943752, -87.658993
get_earthtones(latitude = 41.943752, longitude = -87.658993,
     zoom = 12, number_of_colors = 8)
```

There might be some dependencies missing in the DESCRIPTION file.

**Comment by wcornwell** [comment]
Those are all dependancies of `ggmap`, so somehow it's not following the dependency chain?  Maybe an .Rprofile setting or Rstudio setting or something?  

In any case, `earthtones` as of a few hours ago is on CRAN, so you should be able to just do:

`install.package("earthtones")`
